name: GD Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: iterative/setup-cml@v2

      - name: Install Packages
        run: pip install --upgrade pip && pip install -r requirements.txt && pip install black

      - name: Run Python Script
        run: python gradientDescentAlgorithm.py

      - name: Upload the generated GIF
        uses: actions/upload-artifact@v2
        with:
          name: gradient_descent_animation
          path: gradient_descent_animation.gif
